### ISSUE TITLE
demo_mongo.py results in RuntimeError: Task got Future attached to a different loop

### ISSUE THREAD

**Issue by cygenb0ck** [bmoscon/cryptofeed#421]
**RuntimeError when running example**
`
RuntimeError: Task <Task pending name='Task-1' coro=<FeedHandler._connect() running at PATH/cryptofeed/cryptofeed/feedhandler.py:322>> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.8/asyncio/futures.py:360]> attached to a different loop`

**To Reproduce**
execute examples/demo_mongo.py

**Operating System:**
Ubuntu 20.04.1 LTS

**Cryptofeed Version**
newest version from pip, and also from src github, both behave in the same way

**Comment by bmoscon** [comment]
fixed

**Comment by cygenb0ck** [comment]
thank you!

**Comment by botzill** [comment]
I still get this error when trying the latest version from master.

**Comment by botzill** [comment]
@bmoscon Is there any fix for this issue?

**Comment by bmoscon** [comment]
@botzill - open a ticket and I will take a look. There isnt any context there, just a partial traceback. Please open a ticket and provide more information

**Comment by bmoscon** [comment]
@botzill - also give what is in master another try - I just added another fix for mongo
