### ISSUE TITLE
Bybit BTCUSD perp contract symbol overriden by inverse futures

### ISSUE THREAD

**Issue by CommanderJax** [bmoscon/cryptofeed#445]
bybit_symbols() function is returning incorrect results. The BTC-USD perp contract symbol value gets overriden by inverse futures BTCUSDM21 symbol because the quote and base currencies are the same

steps to reproduce:

```
import nest_asyncio
nest_asyncio.apply()
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback, TradeCallback
from cryptofeed.defines import BID, ASK, L2_BOOK, TRADES
from cryptofeed.exchanges import Bybit
import cryptofeed.symbols 
import requests
from typing import Dict, List, Optional, Tuple
async def trade(feed, symbol, order_id, timestamp, side, amount, price, receipt):
    print(f"Timestamp: {timestamp} Feed: {feed} Pair: {symbol} ID: {order_id} Side: {side} Amount: {amount} Price: {price}")


async def book(feed, symbol, book, timestamp, receipt):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Book Bid Size is {len(book[BID])} Ask Size is {len(book[ASK])}')

SYMBOL_SEP = '-'
def bybit_symbols() -> Dict[str, str]:
    r = None
    try:
        r = requests.get('https://api.bybit.com/v2/public/symbols')
        ret = {}
        for symbol in r.json()['result']:
            print('---')
            print(symbol)
            normalized = f"{symbol['base_currency']}{SYMBOL_SEP}{symbol['quote_currency']}"
            ret[normalized] = symbol['name']
            print(ret)
            print('-+-')
        return ret
    except Exception as why:
        print('BYBIT', why, {"": r})
        
def main():
    bybit_symbols()


if __name__ == '__main__':
    main()
```

result:

> {'BTC-USD': 'BTCUSD'} <----------- OK
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT', 'ADA-USDT': 'ADAUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT', 'ADA-USDT': 'ADAUSDT', 'DOT-USDT': 'DOTUSDT'}
> {'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT', 'ADA-USDT': 'ADAUSDT', 'DOT-USDT': 'DOTUSDT', 'UNI-USDT': 'UNIUSDT'}
> {'BTC-USD': 'BTCUSDM21', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT', 'ADA-USDT': 'ADAUSDT', 'DOT-USDT': 'DOTUSDT', 'UNI-USDT': 'UNIUSDT'}  <----------- NOT OK, BTC-USD == BTCUSDM21

**Comment by bmoscon** [comment]
When did you last update? Pretty sure I fixed this yesterday

**Comment by CommanderJax** [comment]
bummer, updated 2 days ago 🤦‍♂️ 

Thanks.

**Comment by bmoscon** [comment]
@CommanderJax - you should double check that its fixed. I couldnt really tell what your error was due to the formatting of the issue, but I fixed an issue with that symbol not ending in USD/USDT, so do confirm its resolved. If its not, please re-open (and maybe re-format or otherwise clarify the issue)

**Comment by CommanderJax** [comment]
@bmoscon double checked on the latest version, the issue is unfortunately still there. I reformatted my first message, does it make more sense? Sorry I was already tired. For additional context: 

the bybit_symbols() function returns a dictionary of symbols, bybit returns the perp swap together with futures symbols in the same response, both have the same base & quote currency, so in the first iteration the dict contains the correct entry:
{'BTC-USD': 'BTCUSD'}
after the last iteration (as the inverse future contract symbol is the last item in the response it gets overwritten by:
{'BTC-USD': 'BTCUSDM21'}

hope it helps

**Comment by idclevxx** [comment]
First, thanks for a great package @bmoscon! Can confirm the issue is still there. ByBit has launched two new inverse futures contracts, one of which (BTCUSDM21) is overriding the original inverse swap (BTC-USD). Just upgraded and symbols function printed the following:

`{'BTC-USD': 'BTCUSDM21', 'ETH-USD': 'ETHUSD', 'EOS-USD': 'EOSUSD', 'XRP-USD': 'XRPUSD', 'BTC-USDT': 'BTCUSDT', 'BCH-USDT': 'BCHUSDT', 'ETH-USDT': 'ETHUSDT', 'LTC-USDT': 'LTCUSDT', 'LINK-USDT': 'LINKUSDT', 'XTZ-USDT': 'XTZUSDT', 'ADA-USDT': 'ADAUSDT', 'DOT-USDT': 'DOTUSDT', 'UNI-USDT': 'UNIUSDT'}`

Dict needs two new key value pairs, e.g.:
`'BTC-USD_M21':'BTCUSDM21'`
`'BTC-USD_U21':'BTCUSDU21'`

Cheers!

**Comment by bmoscon** [comment]
fixed
