### ISSUE TITLE
demo_liquidation.py timeout

### ISSUE THREAD

**Issue by jzay** [bmoscon/cryptofeed#563]
**Describe the bug**
I'm using the demo_liquidation.py code. Receiving a timeout error and because of that am being rate limited.

2021-07-13 12:51:06,428 : WARNING : BITMEX.ws.1: received no messages within timeout, restarting connection
2021-07-13 12:51:07,413 : WARNING : BITMEX.ws.1: received no messages within timeout, restarting connection
2021-07-13 12:51:08,284 : WARNING : BITMEX.ws.1: Rate Limited - waiting 0 seconds to reconnect
2021-07-13 12:51:09,027 : WARNING : BITMEX.ws.1: Rate Limited - waiting 60 seconds to reconnect

**To Reproduce**
I just ran the liquidation_demo.py file. I had this working find on my old system but I  got a new macbook and now I'm just getting this error.

**Expected behavior**
No timeout errors

**Operating System:**
 - macOS, Python 3.9.6, Cryptofeed 1.9.1

**Cryptofeed Version**
Cryptofeed 1.9.1, installed with pip

**Comment by bmoscon** [comment]
this has been fixed in 1.9.2 (not released in master on github).

**Comment by idclevxx** [comment]
Still getting the error message on both BITMEX and BINANCE after upgrade to 1.9.2.

`WARNING : BITMEX.ws.6: received no messages within timeout, restarting connection`
